teamproject_2/teampr/models.py
from teampr import db
import os
import pandas as pd
import sqlite3
import pymysql
from flask import Flask, render_template, request, session, redirect, url_for


class WineData(db.Model):
    __tablename__ = 'wine_info'
    id = db.Column(db.Integer,primary_key=True)
    prod_name = db.Column(db.String(200), nullable=False)
    winery = db.Column(db.Text(), nullable=False)
    wine_type = db.Column(db.Text(), nullable=False)    
    score = db.Column(db.Float())
    price = db.Column(db.Integer, nullable=False)
    flavor1 = db.Column(db.Text())
    flavor2 = db.Column(db.Text())
    prod_link = db.Column(db.Text(), nullable=False)

class RateBeer(db.Model):
    __tablename__ = 'ratebeer_data'
    index = db.Column(db.Integer, primary_key=True)
    id = db.Column(db.Text(), nullable=False)
    prod_name = db.Column(db.String(200), nullable=False) 
    review_date = db.Column(db.Date(), nullable=False)
    score = db.Column(db.Float(), nullable=False)
    aroma = db.Column(db.Integer())
    appearance = db.Column(db.Integer())
    flavor = db.Column(db.Integer())
    mouthfeel = db.Column(db.Integer())
    overall = db.Column(db.Integer())

class NonAlcoholBeer(db.Model):
    __tablename__ = 'nonalco_beer'
    index = db.Column(db.Integer, primary_key=True)
    prod_name = db.Column(db.String(200), nullable=False) 
    price = db.Column(db.Integer, nullable=False)
    score = db.Column(db.Float(), nullable=False)
    review_text = db.Column(db.Text(), nullable=False)
    review_date = db.Column(db.Date(), nullable=False)
    review_text2 = db.Column(db.Text())

class Whiskey(db.Model):
    __tablename__ = 'whiskey_data'
    index = db.Column(db.Integer, primary_key=True)
    prod_name = db.Column(db.String(200), nullable=False) 
    prod_link = db.Column(db.Text(), nullable=False)
    price = db.Column(db.Integer, nullable=False)
    year = db.Column(db.Integer, nullable=False)
    origin = db.Column(db.String(50), nullable=False)
    volume = db.Column(db.Integer, nullable=False)
    content = db.Column(db.Float(), nullable=False)

teamproject_2/teampr/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SelectMultipleField, widgets
from wtforms.validators import DataRequired

class FilterForm(FlaskForm):
    wine_type = SelectMultipleField('와인 종류', choices=[
        ('red', '레드 와인'),
        ('white', '화이트 와인')
    ])

    price = SelectMultipleField('가격대', choices=[
        ('low', '5만원 이하'),
        ('medium', '10만원 이하'),
        ('high', '15만원 이하')
    ], validators=[DataRequired()])

    score = SelectMultipleField('별점', choices=[
        ('4', '별점 4점 이상'),
        ('3.5', '별점 3.5점 이상'),
        ('3', '별점 3점 이상')
    ], validators=[DataRequired()])

class WhiskeyForm(FlaskForm):
    volume = SelectMultipleField('용량', choices=[
        ('500', '500ml 이상'),
        ('1000', '1000ml 이상')
    ])

    price = SelectMultipleField('가격대', choices=[
        ('low', '20만원 이하'),
        ('medium', '50만원 이하'),
        ('high', '제한 없음')
    ], validators=[DataRequired()])

    year = SelectMultipleField('숙성 기간', choices=[
        ('10', '10년 이상'),
        ('15', '15년 이상'),
        ('20', '20년 이상')
    ], validators=[DataRequired()])

teamproject_2/teampr/__init__.py
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy

import config

db = SQLAlchemy()
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config)

    # ORM
    db.init_app(app)
    migrate.init_app(app, db)
    from . import models
    # 블루프린트
    from .views import main_views
    app.register_blueprint(main_views.bp)

    return app

teamproject_2/teampr/views/main_views.py
from datetime import datetime
from flask import Blueprint, render_template, request, url_for, session
from teampr.models import *
from teampr.forms import *
from werkzeug.utils import redirect
from sqlalchemy import or_
bp = Blueprint('main', __name__, url_prefix='/')


@bp.route('/')
def index():
    wine_list = WineData.query.order_by(WineData.price.desc())
    
    return render_template("index.html", wine_list = wine_list)
@bp.route('/refers')
def refers():
    return render_template("refers.html")


@bp.route('wine/search/', methods=('GET', 'POST'))
def wine_search():
    form = FilterForm()
    if request.method == 'POST' and form.validate_on_submit():
        # db.session.commit()
        session['wine_filtered_data'] = {
            'wine_type': "Red wine" if form.wine_type.data[0] == 'red' else 'White wine',
            'price': 50000 if form.price.data[0] == 'low' else (100000 if form.price.data[0] == 'medium' else 150000),
            'score': 3.0 if form.score.data[0] == '3' else (3.5 if form.score.data[0] == '3.5' else 4.0)
        }
        return redirect(url_for('main.wine_result'))
    return render_template('search/wine_category.html', form = form)

@bp.route('whiskey/search/', methods=('GET', 'POST'))
def whiskey_search():
    form = WhiskeyForm()
    if request.method == 'POST' and form.validate_on_submit():
        # db.session.commit()
        session['whiskey_filtered_data'] = {
            'volume': 500 if form.volume.data[0] == '500' else 1000,
            'price': 200000 if form.price.data[0] == 'low' else (500000 if form.price.data[0] == 'medium' else 2000000),
            'year': 10 if form.year.data[0] == '10' else (15 if form.year.data[0] == '15' else 20)
        }
        return redirect(url_for('main.whiskey_result'))
    return render_template('search/whiskey_category.html', form = form)

@bp.route('beer/search/', methods=('GET', 'POST'))
def beer_search():

    return render_template('index.html')

@bp.route('non_alcohol/search/', methods=('GET', 'POST'))
def non_alcohol_search():

    return render_template('index.html')

@bp.route('wine/search/result/', methods=('GET', 'POST'))
def wine_result():
    wine_filtered_data = session.get('wine_filtered_data')
    wine_type = wine_filtered_data.get("wine_type")
    price = wine_filtered_data.get('price')
    score = wine_filtered_data.get('score')
    filtered_wines = WineData.query.filter(
        WineData.price <= price,
        WineData.wine_type == wine_type,
        WineData.score >= score
    ).all()

    return render_template('search/wine_result.html', filtered_wines=filtered_wines, wine_filter = session.get('wine_filtered_data'))

@bp.route('whiskey/search/result/', methods=('GET', 'POST'))
def whiskey_result():
    whiskey_filtered_data = session.get('filtered_data')
    volume = whiskey_filtered_data.get("volume")
    price = whiskey_filtered_data.get('price')
    year = whiskey_filtered_data.get('year')
    filtered_whiskeys = Whiskey.query.filter(or_(
        Whiskey.volume.isnot(None),
        Whiskey.price.isnot(None),
        Whiskey.year.isnot(None)
        ),
        Whiskey.price <= price,
        Whiskey.volume >= volume,
        Whiskey.year >= year
    ).all()

    return render_template('search/whiskey_result.html',filtered_whiskeys=filtered_whiskeys, whiskey_filter = session.get('whiskey_filtered_data'))

teamproject_2/teampr/templates/base.html
<!DOCTYPE html>
    <html lang="ko">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Search your liquor!</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/reset-css@5.0.2/reset.css" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
            href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;700&family=Roboto:wght@400;500;700&display=swap"
            rel="stylesheet" />
        <link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
        <script defer type="module" src="{{ url_for('static', filename='js/main.js') }}"></script>
        <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap/bootstrap.min.css') }}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css"/>
        <script>
            // 각 체크박스 그룹에 대한 이벤트 처리

            const prices = document.querySelectorAll('input[name="price"]');
            prices.forEach(price => {
                price.addEventListener('click', () => {
                    prices.forEach(cb => {
                        if (cb !== price) {
                            cb.checked = false;
                        }
                    });
                });
            });

            const ratings = document.querySelectorAll('input[name="rating"]');
            ratings.forEach(rating => {
                rating.addEventListener('click', () => {
                    ratings.forEach(cb => {
                        if (cb !== rating) {
                            cb.checked = false;
                        }
                    });
                });
            });
        </script>
        <script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js"></script>
        

    </head>
    <body>
        <!-- header -->
        <header>
            <div class="inner">
                <ul class="menu">
                    <li class="teamname"><a href="{{ url_for('main.index') }}">Find your Liquor!</li>
                    <li><a href="{{ url_for('main.refers') }}">Refer-sites</a></li>
                    <li><a href="{{ url_for('main.wine_search') }}">Wine</a></li>
                    <li><a href="{{ url_for('main.beer_search') }}">Beer</a></li>
                    <li><a href="{{ url_for('main.non_alcohol_search') }}">Non-alchol</a></li>
                    <li><a href="{{ url_for('main.whiskey_search') }}">Whiskey</a></li>
                    <li><a href="#">Teammates</a></li>
                    <li class="search-starter"><a href="javascript:void(0)">검색</a></li>
                </ul>
        </header>
        
        <!-- nav -->
        <!-- <nav>
            <div class="inner">
                <h1>Liquor Search</h1>
                <ul class="menu">
                    <li class="active"><a href="javascript:void(0)">개요</a></li>
                    <li><a href="javascript:void(0)">iPad를 선택하는 이유</a></li>
                    <li><a href="javascript:void(0)">제품 사양</a></li>
                </ul>
                <button class="btn">구입하기</button>
            </div>
        </nav> -->
        <footer>
            <div class="inner">
                <div class="how-to-shop">
                    산대특 2기 2조 '박준영과 아이들' 팀 프로젝트
                </div>
                <div class="legal">
                    <div class="copyright">
                        Copyright © <span class="this-year"></span> Himedia Acadmey
                    </div>
                    <ul>
                        <li><a href="https://github.com/Junyoung-Park-jyp/Teampr_data">github source-code</a></li>
                        <li><a href="javascript:void(0)">크롤링 사이트: Referred 참조</a></li>
                    </ul>
                    <div class="locale">대한민국</div>
                </div>
            </div>
        </footer>
        {% block content %}
        {% endblock %}

    </body>
</html>

teamproject_2/teampr/templates/index.html
{% extends 'base.html' %}

{% block content %}
<div class="swiper-container mySwiper" scrollbar-hide="true">
  <div class="swiper-wrapper">
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/wine1.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/beer2.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/whiskey1.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/wine1.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/beer1.jpg') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/whiskey2.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/wine2.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/beer2.png') }}" alt=""></div>
      <div class="swiper-slide"><img src="{{ url_for('static', filename='image/whiskey1.png') }}" alt=""></div>
  </div>
</div>
<section class="card">
    <div class="inner">
        <!-- beer -->
        <a href="#">
            <div class=" beer floor">
                <div class="container">
                    <h1 class="bgtext">Beer 🍻</h1>
                    <div class="figures">
                        <figure>
                            <!-- <img src="https://e7.pngegg.com/pngimages/756/374/png-clipart-beer-head-graphic-design-illustration-beer-text-beer-bottle.png"
                            alt="keynote 마크업과 메시지가 함께 표시된 Split View" /> -->
                            <figcaption class="bgtext">거침없이 넘어가는 목넘김 <br>오늘 맥주 가능</figcaption>
                        </figure>
                    </div>
                </div>
            </div>
        </a>

        <!-- wine -->
        <a href="#">
            <div class="wine floor">
                <div class="container">
                    <h1 class="bgtext">Wine 🍷</h1>
                    <div class="figures">
                        <figure>
                            <!-- <img src="./images/power_arcade.png" alt="iPad에 Wonderbox 앱이 열려 있는 모습" /> -->
                            <figcaption class="bgtext">신나게 즐기는 새로운 와인찾기</figcaption>
                        </figure>
                    </div>
                </div>
            </div>
        </a>

        <!-- wisky -->
        <a href="#">
            <div class="wisky floor">
                <div class="container">
                    <h1 class="bgtext">Whiskey 🥃</h1>
                    <figure>
                        <!-- <img src="./images/power_create.jpg" alt="Procreate 에서 Apple Pencil로 그림이 그려져 있는 모습" /> -->
                        <figcaption class="bgtext">스카치하고, 그리고,버번하고..</figcaption>
                    </figure>
                </div>
            </div>
        </a>
    </div>
</section>
<script src="https://cdn.jsdelivr.net/npm/swiper@11/swiper-element-bundle.min.js"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
      var mySwiper = new Swiper('.swiper-container', {
          slidesPerView: 3, // 한 번에 표시할 슬라이드 수를 설정 (여기서는 2개로 설정)
          spaceBetween: 20, // 슬라이드 사이의 간격 설정 (옵션)
          loop: true, // 무한 반복 설정
          autoplay: {
              delay: 3000, // 자동 재생 간격 (3초)
              disableOnInteraction: false, // 사용자 상호 작용 후에도 자동 재생 유지
          },
          pagination: {
              el: '.swiper-pagination',
              clickable: true,
          },
          navigation: {
              nextEl: '.swiper-button-next',
              prevEl: '.swiper-button-prev',
          },
      });
  });
</script>
{% endblock %}

teamproject_2/teampr/templates/refers.html
{% extends 'base.html' %}
{% block content %}
<div>
  <div class="row">
      <div class="container_refers col-8"> 
          <div class="card">
              <img src="{{ url_for('static', filename='image/vivino.png') }}" class="card-img-top" alt="...">
              <div class="card-body">
                  <h5 class="card-title">Vivino</h5>
                  <p class="card-text">세계 각지의 와인을 카테고리 별로 검색하고 리뷰 확인 가능</p>
                  <a href="https://www.vivino.com/" class="btn_page">visit page</a>
              </div>
          </div>
      </div>
  </div>
</div>
<div>
  <div class="row">
      <div class="container_refers col-8"> 
          <div class="card">
              <img src="{{ url_for('static', filename='image/ratebeer.png') }}" class="card-img-top" alt="...">
              <div class="card-body">
                  <h5 class="card-title">Ratebeer</h5>
                  <p class="card-text">다양한 맥주와 그에 관한 리뷰를 확인 가능한 세계 최대의 맥주 커뮤니티 중 하나</p>
                  <a href="https://www.ratebeer.com/" class="btn_page">visit page</a>
              </div>
          </div>
      </div>
  </div>
</div>
<div>
  <div class="row">
      <div class="container_refers col-8"> 
          <div class="card">
              <img src="{{ url_for('static', filename='image/kaja.png') }}" class="card-img-top" alt="...">
              <div class="card-body">
                  <h5 class="card-title">가자 주류</h5>
                  <p class="card-text">위스키, 와인 등의 다양한 주류를 다루고 구매할 수 있는 사이트</p>
                  <a href="https://www.kaja.co.kr/" class="btn_page">visit page</a>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

teamproject_2/teampr/templates/search/category.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
  <form method="post" id="filterForm">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items() %}
        <strong>{{ form[field].label }}</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <label for="">와인 종류:</label><br>
    <input type="checkbox" name="wine_type" value="red"> 레드 와인<br>
    <input type="checkbox" name="wine_type" value="white"> 화이트 와인<br>
  
    <label for="">가격대:</label><br>
    <input type="checkbox" name="price" value="low"> 5만원 이하<br>
    <input type="checkbox" name="price" value="medium"> 10만원 이하<br>
    <input type="checkbox" name="price" value="high"> 15만원 이하<br>
  
    <label for="">별점:</label><br>
    <input type="checkbox" name="score" value="4"> 별점 4점 이상<br>
    <input type="checkbox" name="score" value="3.5"> 별점 3.5점 이상<br>
    <input type="checkbox" name="score" value="3"> 별점 3점 이상<br>
  
    <button type="submit">검색</button>
  </form>
</div>
<script>
  // 각 체크박스 그룹에 대한 이벤트 처리
  const prices = document.querySelectorAll('input[name="price"]');
  prices.forEach(price => {
      price.addEventListener('click', () => {
          prices.forEach(cb => {
              if (cb !== price) {
                  cb.checked = false;
              }
          });
      });
  });

  const ratings = document.querySelectorAll('input[name="rating"]');
  ratings.forEach(rating => {
      rating.addEventListener('click', () => {
          ratings.forEach(cb => {
              if (cb !== rating) {
                  cb.checked = false;
              }
          });
      });
  });
</script>
{% endblock %}

teamproject_2/teampr/templates/search/whiskey_category.html
{% extends 'base.html' %}
{% block content %}
<div class="container_refers">
  <form method="post"  id="whiskeyForm">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items() %}
        <strong>{{ form[field].label }}</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="row wine_form">
        <div class="col-4">
            <label for="">용량:</label><br>
            <input type="checkbox" name="volume" value="500"> 500ml 이상<br>
            <input type="checkbox" name="volume" value="1000"> 1000ml 이상<br>
        </div>
        <div class="col-4">
            <label for="">가격대:</label><br>
            <input type="checkbox" name="price" value="low">20만원 이하<br>
            <input type="checkbox" name="price" value="medium">50만원 이하<br>
            <input type="checkbox" name="price" value="high">가격 제한 없음<br>
        </div>
        
        <div class="col-4">
            <label for="">숙성 기간:</label><br>
            <input type="checkbox" name="year" value="10"> 10년 이상<br>
            <input type="checkbox" name="year" value="15"> 15년 이상<br>
            <input type="checkbox" name="year" value="20"> 20년 이상<br>
        </div>

    </div>
    <button type="submit">검색</button>
  </form>
</div>
<script>
  // 각 체크박스 그룹에 대한 이벤트 처리
  const prices = document.querySelectorAll('input[name="price"]');
  prices.forEach(price => {
      price.addEventListener('click', () => {
          prices.forEach(cb => {
              if (cb !== price) {
                  cb.checked = false;
              }
          });
      });
  });

  const ratings = document.querySelectorAll('input[name="rating"]');
  ratings.forEach(rating => {
      rating.addEventListener('click', () => {
          ratings.forEach(cb => {
              if (cb !== rating) {
                  cb.checked = false;
              }
          });
      });
  });
</script>
{% endblock %}

teamproject_2/teampr/templates/search/whiskey_result.html
{% extends 'base.html' %}
{% block content %}

<h1>검색 결과</h1>
{% if whiskey_filter %}
  <h2>검색 조건:</h2>
  <p>용량: {{ whiskey_filter.volume}}ml 이상</p>
  <p>가격대: {{ whiskey_filter.price }}원 이상</p>
  <p>숙성 기간: {{ whiskey_filter.year }}년 이상</p>
{% endif %}
{% for whiskey in filtered_whiskeys %}
{{ whiskey.prod_name }}
{{ whiskey.volume }}
{{ whiskey.price }}
{{ whiskey.year }}

<p></p>
{% endfor %}
{% endblock %}

teamproject_2/teampr/templates/search/wine_category.html
{% extends 'base.html' %}
{% block content %}
<div class="container_refers">
  <form method="post"  id="filterForm">
    {{ form.csrf_token }}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
        {% for field, errors in form.errors.items() %}
        <strong>{{ form[field].label }}</strong>
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="row wine_form">
        <div class="col-4">
            <label for="">와인 종류:</label><br>
            <input type="checkbox" name="wine_type" value="red"> 레드 와인<br>
            <input type="checkbox" name="wine_type" value="white"> 화이트 와인<br>
        </div>
        <div class="col-4">
            <label for="">가격대:</label><br>
            <input type="checkbox" name="price" value="low"> 5만원 이하<br>
            <input type="checkbox" name="price" value="medium"> 10만원 이하<br>
            <input type="checkbox" name="price" value="high"> 15만원 이하<br>
        </div>
        
        <div class="col-4">
            <label for="">별점:</label><br>
            <input type="checkbox" name="score" value="4"> 별점 4점 이상<br>
            <input type="checkbox" name="score" value="3.5"> 별점 3.5점 이상<br>
            <input type="checkbox" name="score" value="3"> 별점 3점 이상<br>
        </div>

    </div>
    <button type="submit">검색</button>
  </form>
</div>
<script>
  // 각 체크박스 그룹에 대한 이벤트 처리
  const prices = document.querySelectorAll('input[name="price"]');
  prices.forEach(price => {
      price.addEventListener('click', () => {
          prices.forEach(cb => {
              if (cb !== price) {
                  cb.checked = false;
              }
          });
      });
  });

  const ratings = document.querySelectorAll('input[name="rating"]');
  ratings.forEach(rating => {
      rating.addEventListener('click', () => {
          ratings.forEach(cb => {
              if (cb !== rating) {
                  cb.checked = false;
              }
          });
      });
  });
</script>
{% endblock %}

teamproject_2/teampr/templates/search/wine_result.html
{% extends 'base.html' %}
{% block content %}


{% if wine_filter %}
  <div class="container_refers">
    <div class="row">
      <div class="card ml-4">
        <div class="card-body">
          <h4>검색 조건</h2>
          <p>와인 종류: {{ wine_filter.wine_type }}</p>
          <p>가격대: {{ wine_filter.price }}원 이하</p>
          <p>별점: {{ wine_filter.score }}점 이상</p>
        </div>
      </div>
    </div>
  </div>
{% endif %}
<h1 class="search_result">검색 결과</h1>
<div class="container_refers lg-10">
  <div class="row lg-10">
  {% for wine in filtered_wines %}
    <div class="col-3">
      <div class="card">
        <div class="card-body col-8">
          <a href="{{ wine.prod_link }}">
            <h5 class="card-title">{{ wine.prod_name }}</h5>
          </a>
          <p class="card-text">와인 종류: {{ wine.wine_type }}</p>
          <p class="card-text">가격: {{ wine.price }}원</p>
          <p class="card-text">별점: {{ wine.score }}점</p>
        </div>
        {% if wine.wine_type == 'Red wine' %}
        <div class="card-body col-3">
          <img src="{{url_for('static', filename='image/redwine.jpg')}}" alt="">
        </div>
        {% endif %}
        {% if wine.wine_type == 'White wine' %}
        <div class="card-body col-3">
          <img src="{{url_for('static', filename='image/whitewine.jpg')}}" alt="">
        </div>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock %}

teamproject_2/teampr/templates/wine_index.html
{% extends 'base.html' %}